# Generated by Django 2.2.1 on 2019-06-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Picture',
            new_name='ProductPicture',
        ),
    ]
