# Generated by Django 2.2.1 on 2019-06-08 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190608_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='caption',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
