# Generated by Django 2.2.2 on 2019-06-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190618_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
