# Generated by Django 2.2.2 on 2019-06-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='size',
        ),
    ]
