# Generated by Django 2.2.2 on 2019-06-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('N/A', 'N/A'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('Small', 'Small (NB)'), ('Large', 'Large (NB)'), ('36', '36'), ('37', '37'), ('38', '38')], default='N/A', max_length=20),
        ),
    ]
